# Generated by Django 4.2.4 on 2023-08-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_rep', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('asunto', models.CharField(default='Asunto del reporte', max_length=300, verbose_name='Asunto del reporte')),
                ('detalles', models.TextField(default='Describe tu reporte tan detallado como sea posible', verbose_name='Detalles del reporte')),
            ],
            options={
                'verbose_name': 'Reportes',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
